# Generated by Django 5.1.5 on 2025-02-17 20:26

import store.utils.user_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniquizbio',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AlterField(
            model_name='miniquizbio',
            name='answer_choices',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='miniquizbio',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='Your password must contain at least 8 characters, including one lowercase letter, one uppercase letter, one digit, and one special character.', max_length=128, validators=[store.utils.user_validator.UserValidator.validate]),
        ),
    ]
