# Generated by Django 5.1.5 on 2025-03-08 19:06

import django.utils.timezone
import store.utils.user_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='Your password must contain at least 8 characters, including one lowercase letter, one uppercase letter, one digit, and one special character.', max_length=128, validators=[store.utils.user_validator.UserValidator.validate]),
        ),
    ]
