# Generated by Django 5.1.5 on 2025-03-09 19:34

import django.db.models.deletion
import store.utils.user_validator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_state_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='Your password must contain at least 8 characters, including one lowercase letter, one uppercase letter, one digit, and one special character.', max_length=128, validators=[store.utils.user_validator.UserValidator.validate]),
        ),
        migrations.CreateModel(
            name='AddressOptional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_optional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
