# Generated by Django 5.1.6 on 2025-03-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description_alter_userprofile_password'),
        ('store', '0002_userprofile_role_alter_userprofile_password_and_more'),
    ]

    operations = [
    ]
