# Generated by Django 5.1.5 on 2025-03-05 20:45

import django.utils.timezone
import store.utils.user_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_address2_address_country_address_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='Your password must contain at least 8 characters, including one lowercase letter, one uppercase letter, one digit, and one special character.', max_length=128, validators=[store.utils.user_validator.UserValidator.validate]),
        ),
    ]
