# Generated by Django 5.1.5 on 2025-03-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_merge_20250316_1803'),
        ('store', '0005_alter_address_phone_number_and_more'),
    ]

    operations = [
    ]
