# Generated by Django 5.1.5 on 2025-04-10 17:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 17, 18, 3, 155372, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiz_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiscountVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 10, 17, 18, 3, 157386, tzinfo=datetime.timezone.utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
