# Generated by Django 5.1.5 on 2025-04-10 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userprofile_expiration_date_userprofile_quiz_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 10, 17, 22, 55, 543048, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 17, 22, 55, 541122, tzinfo=datetime.timezone.utc)),
        ),
    ]
