# Generated by Django 5.1.5 on 2025-04-12 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_discountvoucher_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_quiz_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 12, 11, 15, 50, 89590, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 11, 15, 50, 86543, tzinfo=datetime.timezone.utc)),
        ),
    ]
