# Generated by Django 5.1.5 on 2025-05-19 16:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_userprofile_last_quiz_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 18, 16, 26, 13, 800811, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 16, 26, 13, 797152, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'user')},
            },
        ),
    ]
