from store.mini_quiz_bio.making_class_question_answer import MakingQuestionAnswer

list_of_question = [
    MakingQuestionAnswer("What does BIO stand for on food products?", "Biological Organisational Innovation",
                          "Biologically isolated organism", "Biologically Intensive Observation", "Biological",
                          "d"),
    MakingQuestionAnswer("Which certification is most commonly used for organic food in Europe?",
                          "Fair Trade", "Rainforest Alliance", "EuroLeaf", "USDA Organic", "c"),
    MakingQuestionAnswer("Which of the following products can be labelled as BIO?",
                          "Products made without pesticides and GMOs", "Products containing synthetic additives",
                          "Products imported from non-European countries", "All products available for sale",
                          "a"),
    MakingQuestionAnswer("How does organic farming affect the environment?", "Increases water consumption",
                          "Pollutes soil and water", "Reduces biodiversity",
                          "Reduces pollution and promotes biodiversity", "d"),
    MakingQuestionAnswer("Which ingredient is prohibited in organic food?", "Sugar",
                          "Synthetic pesticides", "Natural ingredients", "Vitamins", "b"),
    MakingQuestionAnswer("What is the main principle of BIO food production?", "Using only local products",
                          "Minimising the use of chemicals and GMOs", "Production only in specific regions",
                          "Limiting international distribution", "b"),
    MakingQuestionAnswer("What health benefits are often attributed to BIO foods?", "More preservatives",
                          "Contains more pesticides", "Higher nutrient content",
                          "Increased durability", "c"),
    MakingQuestionAnswer("What methods of weed control are used in organic farming?",
                          "Use of chemical herbicides", "Crop rotation and manual weeding", "Use of GMOs",
                          "Introduction of predators", "b"),
    MakingQuestionAnswer("Which of the following is not required for a product to be labelled as BIO?",
                          "Production quality control", "Avoidance of GMOs", "Use of chemical preservatives",
                          "Certification by a relevant authority", "c"),
    MakingQuestionAnswer("What label can you find on organic products in Poland?", "Safe Product",
                           "EcoCert", "EuroLeaf", "Eco Poland", "c"),
    ]
