from mini_quiz_bio.making_class_question_answer import MakingQuestionAnswer

list_of_questions = [
    MakingQuestionAnswer("Co oznacza skrót BIO na produktach spożywczych?", "Biologiczne Innowacje Organizacyjne",
                          "Biologicznie Izolowane Organizmy", "Biologicznie Intensywna Obserwacja", "Biologiczne",
                          "d"),
    MakingQuestionAnswer("Który certyfikat jest najczęściej stosowany dla żywności ekologicznej w Europie?",
                          "Fair Trade", "Rainforest Alliance", "EuroLeaf", "USDA Organic", "c"),
    MakingQuestionAnswer("Które z poniższych produktów mogą być oznaczone jako BIO?",
                          "Produkty wytworzone bez pestycydów i GMO", "Produkty zawierające syntetyczne dodatki",
                          "Produkty importowane z krajów pozaeuropejskich", "Wszystkie produkty dostępne w sprzedaży",
                          "a"),
    MakingQuestionAnswer("W jaki sposób rolnictwo ekologiczne wpływa na środowisko?", "Zwiększa zużycie wody",
                          "Zanieczyszcza glebę i wodę", "Ogranicza bioróżnorodność",
                          "Ogranicza zanieczyszczenie i sprzyja bioróżnorodności", "d"),
    MakingQuestionAnswer("Który składnik jest zabroniony w żywności ekologicznej?", "Cukier",
                          "Pestycydy syntetyczne", "Składniki naturalne", "Witaminy", "b"),
    MakingQuestionAnswer("Co jest główną zasadą produkcji BIO żywności?", "Stosowanie tylko lokalnych produktów",
                          "Minimalizacja użycia chemikaliów i GMO", "Produkcja wyłącznie w określonych regionach",
                          "Ograniczenie dystrybucji międzynarodowej", "b"),
    MakingQuestionAnswer("Jakie korzyści zdrowotne często przypisuje się BIO żywności?", "Większa ilość konserwantów",
                          "Zawiera więcej pestycydów", "Większa zawartość składników odżywczych",
                          "Większa trwałość", "c"),
    MakingQuestionAnswer("Jakie metody kontroli chwastów są stosowane w rolnictwie ekologicznym?",
                          "Użycie herbicydów chemicznych", "Rotacja upraw i ręczne odchwaszczanie", "Stosowanie GMO",
                          "Wprowadzenie drapieżników", "b"),
    MakingQuestionAnswer("Które z poniższych nie jest wymagane, aby produkt był oznaczony jako BIO?",
                          "Kontrola jakości produkcji", "Unikanie GMO", "Użycie chemicznych konserwantów",
                          "Certyfikacja przez odpowiednie organy", "c"),
    MakingQuestionAnswer("Jakie oznaczenie znajdziesz na produktach ekologicznych w Polsce?", "Produkt Bezpieczny",
                           "EcoCert", "EuroLiść", "Eko Polska", "c"),
    ]
