STATES = [
    ("", "Choose..."),
    ("dolnoslaskie", "Dolnośląskie"),
    ("kujawsko-pomorskie", "Kujawsko-pomorskie"),
    ("lubelskie", "Lubelskie"),
    ("lubuskie", "Lubuskie"),
    ("lodzkie", "Lódzkie"),
    ("malopolskie", "Małopolskie"),
    ("mazowieckie", "Mazowieckie"),
    ("opolskie", "Opolskie"),
    ("podkarpackie", "Podkarpackie"),
    ("podlaskie", "Podlaskie"),
    ("pomorskie", "Pomorskie"),
    ("slaskie", "Śląskie"),
    ("swietokrzyskie", "Świętokrzyskie"),
    ("warminsko-mazurskie", "Warmińsko-mazurskie"),
    ("wielkopolskie","Wielkopolskie"),
    ("zachodniopomorskie", "Zachodniopomorskie"),
]
